import React from 'react';
import PropTypes from 'prop-types';
import { Tab, Tabs, TabList, TabPanel } from 'react-tabs';
import 'react-tabs/style/react-tabs.less';

import { mapboxAPIToken } from '../localconf';
import WorldMapChart from './WorldMapChart';
import IllinoisMapChart from './IllinoisMapChart';
import CountWidget from './CountWidget';
import PlotChart from './PlotChart';
import './Covid19Dashboard.less';


// |-----------------------------------|
// | Data Commons logo, title, buttons |
// |-----------------------------------|
// | World Tab | IL Tab |              |
// |-----------------------------------|
// |   # of cases   |   # of deaths    |
// |-----------------------------------|
// |                         |  Chart  |
// |                         |         |
// |           Map           |---------|
// |                         |  Chart  |
// |                         |         |
// |-----------------------------------|
//
// Config:
// "covid19DashboardConfig": {
//   "dataUrl": "",
//   "enableCharts": true/false
// },


/* To fetch new data:
- add the prop name and location to `dashboardDataLocations`;
- add the prop to Covid19Dashboard.propTypes;
- add it to ReduxCovid19Dashboard.handleDashboardData().
*/
const dashboardDataLocations = {
  jhuGeojsonLatest: 'map_data/jhu_geojson_latest.json',
  jhuJsonByLevelLatest: 'map_data/jhu_json_by_level_latest.json',
  seirObserved: 'observed_cases.txt',
  seirSimulated: 'simulated_cases.txt',
  top10: 'top10.txt',
  idphDaily: 'idph_daily.txt',
};

class Covid19Dashboard extends React.Component {
  constructor(props) {
    super(props);
    this.enableCharts = !!props.config.enableCharts;
  }

  componentDidMount() {
    if (!mapboxAPIToken) {
      console.warn('MAPBOX_API_TOKEN environment variable not set, will be unable to load maps.'); // eslint-disable-line no-console
    }

    Object.entries(dashboardDataLocations).forEach(
      e => this.props.fetchDashboardData(e[0], e[1]),
    );
  }

  getTotalCounts() {
    // find latest date we have in the data
    const confirmedCount = {
      global: 0,
      illinois: 0,
    };
    const deathsCount = {
      global: 0,
      illinois: 0,
    };
    const recoveredCount = {
      global: 0,
      illinois: 0,
    };

    this.props.jhuGeojsonLatest.features.forEach((feat) => {
      const confirmed = +feat.properties.confirmed;
      const deaths = +feat.properties.deaths;
      const recovered = +feat.properties.recovered;
      if (confirmed) {
        confirmedCount.global += confirmed;
        if (feat.properties.province_state === 'Illinois') {
          confirmedCount.illinois += confirmed;
        }
      }
      if (deaths) {
        deathsCount.global += deaths;
        if (feat.properties.province_state === 'Illinois') {
          deathsCount.illinois += deaths;
        }
      }
      if (recovered) {
        recoveredCount.global += recovered;
        if (feat.properties.province_state === 'Illinois') {
          recoveredCount.illinois += recovered;
        }
      }
    });

    return { confirmedCount, deathsCount, recoveredCount };
  }

  getPlotChartsConfig() {
    const displaySeirPlot = Object.keys(this.props.seirObserved).length > 0
      && Object.keys(this.props.seirSimulated).length > 0;
    const seirPlotChart = [
      {
        data: this.props.seirObserved,
        name: 'Observed Cases',
      },
      {
        data: this.props.seirSimulated,
        name: 'Simulated Cases',
      },
    ];
    const seirChart = displaySeirPlot ? (<PlotChart
      title='Forecasting COVID-19 cases with a SEIR model'
      xTitle='Date'
      yTitle='Population'
      description='The simulated cases (blue curve) generated by the SEIR model is consistent with the observed cases (orange curve). The orange curve also shows the forecasted cases for 14 days.'
      plots={seirPlotChart}
    />) : null;

    const displayTop10Plot = Object.keys(this.props.top10).length > 0;
    const top10ChartPlots = Object.entries(this.props.top10).map(([key, value]) => ({
      data: value,
      name: key,
    }),
    );
    const top10Chart = displayTop10Plot ? (<PlotChart
      title='Daily Confirmed Cases (5-day Moving Average)'
      xTitle='Date'
      yTitle='Confirmed New Cases'
      description=''
      plots={top10ChartPlots}
    />) : null;

    const displayIdphDailyChart = Object.keys(this.props.idphDaily).length > 0;
    const idphDailyChartPlots = Object.entries(this.props.idphDaily).map(([key, value]) => ({
      data: value,
      name: key,
    }),
    );
    const idphDailyChart = displayIdphDailyChart ? (<PlotChart
      title='Breakdown of Tests, Cases and Deaths in Illinois Over Time'
      xTitle='Date'
      yTitle='# of Tests/Cases/Deaths'
      description=''
      plots={idphDailyChartPlots}
    />) : null;

    return { seirChart, top10Chart, idphDailyChart };
  }

  render() {
    const {
      confirmedCount, deathsCount, recoveredCount,
    } = this.getTotalCounts();
    const {
      seirChart, top10Chart, idphDailyChart,
    } = this.enableCharts ? this.getPlotChartsConfig() : {};

    return (
      <div className='covid19-dashboard'>
        {/* <ReactEcharts
          option={this.getOption()}
          style={{height: '500px', width: '100%'}}
        /> */}
        <div>
          <Tabs>
            <TabList className='covid19-dashboard_tablist'>
              <Tab>COVID-19 in the world</Tab>
              <Tab>COVID-19 in Illinois</Tab>
            </TabList>

            <TabPanel className='covid19-dashboard_panel'>
              <div className='covid19-dashboard_counts'>
                <CountWidget
                  label='Total Confirmed'
                  value={confirmedCount.global}
                />
                <CountWidget
                  label='Total Deaths'
                  value={deathsCount.global}
                />
                <CountWidget
                  label='Total Recovered'
                  value={recoveredCount.global}
                />
              </div>
              <div className='covid19-dashboard_visualizations'>
                <WorldMapChart
                  geoJson={this.props.jhuGeojsonLatest}
                  jsonByLevel={this.props.jhuJsonByLevelLatest}
                />
                {this.enableCharts &&
                  <div className='covid19-dashboard_charts'>
                    {top10Chart}
                  </div>
                }
              </div>
            </TabPanel>

            <TabPanel className='covid19-dashboard_panel'>
              <div className='covid19-dashboard_counts'>
                <CountWidget
                  label='Total Confirmed'
                  value={confirmedCount.illinois}
                />
                <CountWidget
                  label='Total Deaths'
                  value={deathsCount.illinois}
                />
              </div>
              <div className='covid19-dashboard_visualizations'>
                <IllinoisMapChart
                  jsonByLevel={this.props.jhuJsonByLevelLatest}
                />
                {this.enableCharts &&
                  <div className='covid19-dashboard_charts'>
                    {seirChart}
                    {idphDailyChart}
                  </div>
                }
              </div>
            </TabPanel>
          </Tabs>
        </div>
      </div>
    );
  }
}

Covid19Dashboard.propTypes = {
  config: PropTypes.object.isRequired,
  fetchDashboardData: PropTypes.func.isRequired,
  jhuGeojsonLatest: PropTypes.object,
  jhuJsonByLevelLatest: PropTypes.object,
  seirObserved: PropTypes.object,
  seirSimulated: PropTypes.object,
  top10: PropTypes.object,
  idphDaily: PropTypes.object,
};

Covid19Dashboard.defaultProps = {
  jhuGeojsonLatest: { type: 'FeatureCollection', features: [] },
  jhuJsonByLevelLatest: { country: {}, state: {}, county: {} },
  seirObserved: {},
  seirSimulated: {},
  top10: {},
  idphDaily: {},
};

export default Covid19Dashboard;
