// App is: bhc
//
// !!! DO NOT EDIT !!!!
//
// This file was auto-generated by: node data/gqlSetup.js 
// using the Nunjucks template at data/gqlHelper.js.njx
//      https://mozilla.github.io/nunjucks/
//

import Relay from 'react-relay/classic';
import {app,dev} from './localconf.js';
import {graphql} from 'react-relay';



/**
 * gql database
 */
const helperSingleton = {
  /**
   * Fetch the initial list of projects and global node counts
   */
  homepageQuery: graphql`query gqlHelperHomepageQuery {
        projectList: project(first: 10000) {
          name: project_id
          code
          experimentCount: _studies_count
        }
        caseCount: _case_count
        experimentCount:  _study_count
        aliquotCount: _aliquot_count
        
        fileCount1: _slide_image_count
        fileCount2: _submitted_aligned_reads_count
        fileCount3: _submitted_copy_number_count
        fileCount4: _submitted_methylation_count
        fileCount5: _submitted_somatic_mutation_count
        fileCount6: _submitted_unaligned_reads_count
        fileCount7: _app_checkup_count
        fileCount8: _cell_image_count
        fileCount9: _clinical_checkup_count
        fileCount10: _derived_checkup_count
        fileCount11: _mass_cytometry_assay_count
        fileCount12: _mass_cytometry_image_count
        fileCount13: _mri_result_count
        fileCount14: _sensor_checkup_count
        fileCount15: _test_result_count
    }`,
  
    projectDetailQuery: graphql`query gqlHelperProjectDetailQuery( $name: [String] ) {
        project( project_id:$name ) {
          name: project_id
          code
          experimentCount:  _studies_count
        }
        caseCount: _case_count( project_id:$name )
        experimentCount: _study_count( project_id:$name )
        aliquotCount: _aliquot_count( project_id:$name )
        
        fileCount1: _slide_image_count( project_id:$name )
        fileCount2: _submitted_aligned_reads_count( project_id:$name )
        fileCount3: _submitted_copy_number_count( project_id:$name )
        fileCount4: _submitted_methylation_count( project_id:$name )
        fileCount5: _submitted_somatic_mutation_count( project_id:$name )
        fileCount6: _submitted_unaligned_reads_count( project_id:$name )
        fileCount7: _app_checkup_count( project_id:$name )
        fileCount8: _cell_image_count( project_id:$name )
        fileCount9: _clinical_checkup_count( project_id:$name )
        fileCount10: _derived_checkup_count( project_id:$name )
        fileCount11: _mass_cytometry_assay_count( project_id:$name )
        fileCount12: _mass_cytometry_image_count( project_id:$name )
        fileCount13: _mri_result_count( project_id:$name )
        fileCount14: _sensor_checkup_count( project_id:$name )
        fileCount15: _test_result_count( project_id:$name )
    }`,

    explorerPageQuery: graphql`query gqlHelperExplorerPageQuery{
        viewer {
            ...gqlHelperExplorerFragment
        }
    }`,

    explorerPageFragment: graphql.experimental`
    fragment gqlHelperExplorerFragment on viewer
    @argumentDefinitions(
        selected_projects: {type: "[String]"},
        selected_file_types: {type: "[String]"},
        selected_file_formats: {type: "[String]"}
    )
    {
      
      fileData1:slide_image(first: 10000, project_id: $selected_projects, data_type: $selected_file_types, data_format: $selected_file_formats) {
        project_id
        file_name
        data_category
        data_format
        data_type
        file_size
      }
      fileData2:submitted_aligned_reads(first: 10000, project_id: $selected_projects, data_type: $selected_file_types, data_format: $selected_file_formats) {
        project_id
        file_name
        data_category
        data_format
        data_type
        file_size
      }
      fileData3:submitted_copy_number(first: 10000, project_id: $selected_projects, data_type: $selected_file_types, data_format: $selected_file_formats) {
        project_id
        file_name
        data_category
        data_format
        data_type
        file_size
      }
      fileData4:submitted_methylation(first: 10000, project_id: $selected_projects, data_type: $selected_file_types, data_format: $selected_file_formats) {
        project_id
        file_name
        data_category
        data_format
        data_type
        file_size
      }
      fileData5:submitted_somatic_mutation(first: 10000, project_id: $selected_projects, data_type: $selected_file_types, data_format: $selected_file_formats) {
        project_id
        file_name
        data_category
        data_format
        data_type
        file_size
      }
      fileData6:submitted_unaligned_reads(first: 10000, project_id: $selected_projects, data_type: $selected_file_types, data_format: $selected_file_formats) {
        project_id
        file_name
        data_category
        data_format
        data_type
        file_size
      }
      fileData7:app_checkup(first: 10000, project_id: $selected_projects, data_type: $selected_file_types, data_format: $selected_file_formats) {
        project_id
        file_name
        data_category
        data_format
        data_type
        file_size
      }
      fileData8:cell_image(first: 10000, project_id: $selected_projects, data_type: $selected_file_types, data_format: $selected_file_formats) {
        project_id
        file_name
        data_category
        data_format
        data_type
        file_size
      }
      fileData9:clinical_checkup(first: 10000, project_id: $selected_projects, data_type: $selected_file_types, data_format: $selected_file_formats) {
        project_id
        file_name
        data_category
        data_format
        data_type
        file_size
      }
      fileData10:derived_checkup(first: 10000, project_id: $selected_projects, data_type: $selected_file_types, data_format: $selected_file_formats) {
        project_id
        file_name
        data_category
        data_format
        data_type
        file_size
      }
      fileData11:mass_cytometry_assay(first: 10000, project_id: $selected_projects, data_type: $selected_file_types, data_format: $selected_file_formats) {
        project_id
        file_name
        data_category
        data_format
        data_type
        file_size
      }
      fileData12:mass_cytometry_image(first: 10000, project_id: $selected_projects, data_type: $selected_file_types, data_format: $selected_file_formats) {
        project_id
        file_name
        data_category
        data_format
        data_type
        file_size
      }
      fileData13:mri_result(first: 10000, project_id: $selected_projects, data_type: $selected_file_types, data_format: $selected_file_formats) {
        project_id
        file_name
        data_category
        data_format
        data_type
        file_size
      }
      fileData14:sensor_checkup(first: 10000, project_id: $selected_projects, data_type: $selected_file_types, data_format: $selected_file_formats) {
        project_id
        file_name
        data_category
        data_format
        data_type
        file_size
      }
      fileData15:test_result(first: 10000, project_id: $selected_projects, data_type: $selected_file_types, data_format: $selected_file_formats) {
        project_id
        file_name
        data_category
        data_format
        data_type
        file_size
      }
    }
  `,
  explorerRefreshQuery: graphql.experimental`
    query gqlHelperExplorerRefreshQuery (
      $selected_projects: [String],
      $selected_file_types: [String],
      $selected_file_formats: [String]
    )
    {
      viewer {
        ...gqlHelperExplorerFragment @arguments(selected_projects: $selected_projects,
            selected_file_types: $selected_file_types,
            selected_file_formats: $selected_file_formats
        )
      }
    }
  `,
};


//----------------------------------------------

/**
 * App-aware GQLHelper - delegates to the appropriate helper for the given app
 * based on a compile-time transformation. Relay does not like gql that
 * does not conform to the schema supplied to the relay compiler, so to
 * support different dictionaries in the same app we need to be a little
 * bit clever. 
 */
export class GQLHelper {
  /**
   * Goofy little utility - scans data for keys matching 'fileCount\d+' or 'fileData\d+',
   * and returns a { fileCount: sum-of-fileCounts, fileData:[] concatenation of data }
   * 
   * @param {Object} data
   * @return {fileCount:sum,fileData:Array} 
   */
  static extractFileInfo( data ) {
    const fileCount = Object.keys( data ).filter( key => key.indexOf( "fileCount" ) === 0 ).map( key => data[key] 
    ).reduce( (acc,it) => acc + it, 0 );
    const fileData = Object.keys( data ).filter( key => key.indexOf( "fileData" ) === 0 ).map( key => data[key] 
    ).reduce( 
      (acc,it) => { let result=acc; if( Array.isArray( it ) ) { result = acc.concat( it ) } else { acc.push(it ); } return result }, 
      [] 
    );
    return { fileCount: fileCount, fileData: fileData };
  }


  /**
   * Little singleton factory 
   */
  static getGQLHelper( appName=app ) {
    return helperSingleton;
  }
    
}



